pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                // npm test
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                // npm run build + save process id in pidfile
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                // kill process id from pidfile
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
